Fixes for nested parallelism and tasking runtime
Contributors: Deepak

There were a number of issues with the nested region support in the OpenMP
runtime that needed to be addressed, especially with regard to supporting
explicit tasks for nested thread teams. There were also a variety of other
bugs in the tasking implementation to be fixed.

- Fix level 1 team expansion for tasks.  Fixes the expansion of threads in
  level 1 team for tasks. Before, __omp_level_1_team_tasks,
  __omp_local_task_q, and __omp_private_task_q were allocated in
  __ompc_init_rtl and never resized, which could result in a crash if a region
  forks more threads than initially created at startup.

- Changes the type definition of omp_task_t, moving fields that were
  previously placed in s_coroutine into omp_task_t instead. Before, omp_task_t
  was just typedef coroutine_t. Now, omp_task_t is defined as:

    struct omp_task { coroutine_t coro; struct omp_task *creator; struct
    omp_task *next; struct omp_task *prev; omp_task_desc_t *desc;
    pthread_mutex_t lock; };

    //typedef coroutine omp_task_t;
    typedef struct omp_task omp_task_t;

  Where, omp_task_desc_t is a task descriptor type:

    /*structure representing tasks is in pcl.h */
    struct omp_task_desc { volatile uint32_t num_children; int
    is_parallel_task; int is_tied; int started; volatile omp_task_state_t
    state; volatile int safe_to_enqueue; int depth; int pdepth; volatile int
    context_flag; int threadid; };

    typedef struct omp_task_desc omp_task_desc_t;

  I modified the implementation in omp_thread.c, omp_thread.h, omp_task.c, and
  omp_task.h accordingly. Also, note that while before
  __omp_level_1_team_tasks had type omp_task_t **, it is now omp_task_t * (an
  array of structs, similar to the __omp_level_1_team and
  __omp_level_1_pthread data structures).

- Fix for forking threads in nested region.  When forking threads for a
  parallel region in __ompc_fork, there is a loop which prepares the attribute
  data structure (__omp_pthread_attr) for each pthread being created.  For
  level 1 regions, this loop updates it with a new stack pointer on each
  iteration and then creates the pthread.

  For nested regions where multiple threads could be spawning their parallel
  regions simultaneously, it can't use a single attribute data structure (when
  updating, they clobber eachother). Instead, create a nested_pthread_attr
  that is local to __ompc_fork, and use this to set up the pthread attributes
  for nested regions.

  Also, before if num_threads == 0, it was set to the level 1 team size.
  Actually, as per the spec it should be set to __ompc_get_max_threads, so
  this was changed.

- Adds support for tasks in nested teams.  We associate implicit tasks and
  task queues with user threads and OpenMP teams, respecitively. Adds an
  implicit_task to the omp_v_thread struct. Therefore, every thread has a
  reference to its implicit task regardless of whether it is level 1 or nested
  team. Also, private_task_q and public_task_q are added to omp_team type. The
  implementation now uses implicit_task, private_task_q, and public_task_q for
  referring to and scheduling tasks.

  A number of other fixes were necessary to prevent hanging or seg faults when
  explicit tasks are used in nested parallel regions. In summary:

  * Allocate __omp_exe_mode in thread local storage, instead of global. This
    is necessary because with nested parallelism some threads may be in
    OMP_EXE_MODE_NORMAL while others may be in OMP_EXE_MODE_NESTED, so a
    global __omp_exe_mode won't work. Also, needed to set __omp_exe_mode for
    level 1 and nested slave threads.

  * Fix behavior in barrier at end of nested parallel region so that it
    completes any pending tasks in the team.

  * Added call to __ompc_init_vp() in nested slave threads, as they are of
    course not initialized at startup.

  * Free task queues for nested team at completion of their region.

  * Set __omp_myid for master thread of nested regions, and restore original
    id at the end of the region.

- Handle task construct when when in SEQUENTIAL execution mode. We initialize
  the implicit task in __omp_root_v_thread, and have __omp_current_task point
  to it. So, all explicit tasks in sequential region have a non-NULL creator.

  This commit also fixes a bug relating to parent-child more generally, where
  there is a seg fault when switching back to the parent task after child
  exits.  When it called __ompc_task_switch, instead of passing NULL for the
  'old_task' parameter, it should pass a pointer to the child.

- Removes inline from __ompc_ebarrier declaration.  This was declared as
  inline before, but with gcc > 4.3 this results in __ompc_ebarrier not being
  emitted. This caused an error "undefined reference to '__ompc_ebarrier'"
  when compiling programs with a barrier directive.

- Don't set Force_Frame_Pointer for nested parallelism.  In earlier
  implementation, Force_Frame_Pointer and Force_Frame_Pointer_Set needed to be
  set to true for nested parallelism to work in x86_64. It doesn't appear to
  be necessary anymore, so removing this.

- Ignore WN_PRAGMA_COPYIN_BOUND in parallel region.  If there is struct array
  local to a parallel region, compiler generates an xpragma for COPYIN_BOUND.
  For debug build, compiler throw an assertion error on encountering this.
  Adding a case in Transform_Parallel_Block to ignore it.

- Fix for immediate task. Implementation was hanging or seg faulting when task
  if clause was used. The implementation for handling undeferred tasks was not
  correct. This was fixed by enqueuing parent into private or public queue,
  depending on whether it is tied or not, and also setting implicit tasks as
  tied.

- Fix to allow arbitrary MP nesting levels in PU.  In cgemit.cxx, it assumes
  the maximum nesting depth for symbol table scopes is 6:

    /*
     * Maximum nesting depth includes these scopes, in the deepest case: 0 :
     * not used 1 : global scope 2 : top-level PU 3 : F90 internal procedure 4
     * : MP PU from internal procedure 5 : Fortran I/O in MP PU
     */

    #define MAX_SYMTAB_DEPTH    6

    static INT32 *elf_index_array[MAX_SYMTAB_DEPTH] =
    {NULL,NULL,NULL,NULL,NULL,NULL}; static INT
    max_elf_index[MAX_SYMTAB_DEPTH] = {0,0,0,0,0,0};

  Because we implement nested parallel regions and tasks as nested PUs, for us
  the nesting depth can be arbitrarily deep. So, we modify cgemit to grow
  elf_index_array and max_elf_index as needed using vector type instead of
  static arrays.

- Additions to aid in debugging. Adds a routine __dump_task_q to dump the
  contents of a task queue.

- Fix for explicit tasks outside of parallel region. Task queues were not
  allocated before first call to __ompc_fork, but __ompc_task_create was
  trying to access them even when in sequential exec mode. We allocate task
  queues in __ompc_init_rtl itself for the initial level 1 thread team.

  Also, for __ompc_task_body_start, don't switch back to the parent task if
  may_delay was 0 or its sequential mode.

- Fixes threadprivate support for nested task regions. Cleans up the
  threadprivate translation in the compiler for nested tasks. Threadprivate
  still does not work correctly for nested parallel regions.

- Fix for setting started and threadid field for tied task. The started and
  threadid fields for the tied task should be set after __ompc_task_body_start
  is called, to ensure that it is set on the thread to which the task will be
  tied to. Origially, these fields were instead set in __ompc_task_switch and
  __ompc_task_exit_to, as per Cody Addison's original tasking design.  This
  resulted in a tied task being placed in the wrong private queue of the
  thread on which it was created when leaving the SUSPENDED state, instead of
  the thread to which it is tied,  which is clearly wrong.

git-svn-id: http://svn.open64.net/svnroot/open64@3670 ead328b1-e903-0410-a19d-eacee4b031f6