Fix bugs 15589 and 15680: ICE during Localize phase for code using regparm.
We observed this error when compiling code that uses the GNU i386-specific
regparm attribute applied to function pointers, for example the Expat
library, with low optimization levels:

Signal: Segmentation fault in Localize phase.
Error: Signal Segmentation fault in phase Localize -- processing aborted

The error occurred because one of the checks in Check_If_Dedicated_TN_Is_Global
did not handle the ICALL case, where CALLINFO_call_st is expected to return
NULL.

This update makes the check more robust and since it's more complicated, moves
the logic into the helper routine Return_Via_First_Arg.

In addition, the regparm attribute was not being respected by
Check_If_Dedicated_TN_Is_Global, which would "localize" arguments passed in
RDX and RCX.  The new check encapsulated in Is_Regparm_Call was added to detect
this case.



git-svn-id: http://svn.open64.net/svnroot/open64@3188 ead328b1-e903-0410-a19d-eacee4b031f6